/**
 * Weight configuration types
 * Represents achievement network algorithm weight parameters
 */

export type RelationshipType =
  | 'PHD_ADVISOR' // PhD advisor
  | 'PAPER_COAUTHOR' // Paper co-author
  | 'OPEN_SOURCE_COLLABORATOR' // Open source collaborator
  | 'COLLEAGUE' // Colleague
  | 'LABMATE' // Lab mate

export interface WeightConfig {
  // Unique identifier
  id?: string // Optional, used for saving multiple configs
  name?: string // Configuration name, e.g. "Default Config", "Test Config 1"
  description?: string // Configuration description
  created_at?: string // Creation time (ISO 8601)
  updated_at?: string // Update time (ISO 8601)

  // 第1组: 关系类型权重（8种关系）
  relationship_multipliers?: {
    PHD_ADVISOR?: number // 导师关系 (default: 1.5)
    LABMATE?: number // 实验室同事 (default: 1.3)
    PAPER_COAUTHOR?: number // 论文合著者 (default: 1.2)
    OPEN_SOURCE_COLLABORATOR?: number // 开源协作者 (default: 1.0)
    COLLEAGUE?: number // 同事关系 (default: 1.1)
    FORMER_COLLEAGUE?: number // 前同事 (default: 0.9)
    ALUMNI?: number // 校友 (default: 0.8)
    SKILL_DOMAIN_EXPERT?: number // 技能领域专家 (default: 0.7)
  }

  // 第2组: 影响力归一化参数
  impact_normalization?: {
    github_divisor?: number // GitHub stars除数 (default: 10000)
    openreview_divisor?: number // Citations除数 (default: 100)
  }

  // 第3组: 频率vs影响力平衡
  frequency_impact_balance?: {
    frequency?: number // 频率权重 (default: 0.5)
    impact?: number // 影响力权重 (default: 0.5)
  }

  // 第4组: 时间衰减配置
  time_decay?: {
    decay_rate?: number // 衰减率 (default: 0.2)
    recent_threshold?: number // 近期阈值（年） (default: 3)
  }

  // 第5组: 数据源置信度
  source_confidence?: {
    github?: number // GitHub 置信度 (default: 0.90)
    openreview?: number // OpenReview 置信度 (default: 0.95)
  }

  // 人名匹配阈值
  name_matching?: {
    fuzzy_threshold?: number // 人名模糊匹配阈值 (default: 0.85)
  }
}

export interface AchievementNode {
  name: string // Person name
  github_login?: string // GitHub username (optional)
  github_username?: string // GitHub username (alternative field name)
  relationship_type: RelationshipType // Relationship type
  closeness_score: number // Closeness score (0-10)
  final_score: number // Final score (after applying weights)
  reason?: string // Relationship reason description (legacy field)
  reason_for_inclusion?: string // Relationship reason description (new field)
  source?: 'github' | 'openreview' | 'websearch' | 'linkedin' // Data source (legacy, singular)
  sources?: string[] // Data sources (new, array format)
  metadata?: Record<string, any> // Metadata (e.g. position, company, contributions)

  // Additional fields
  affiliation?: string // Organization/affiliation
  avatar_url?: string // Avatar URL
  collaboration_frequency?: number // Collaboration frequency (times)
  collaboration_time?: string // Collaboration time period
  representative_collaboration?: {
    type: 'Repository' | 'Publication' | 'Collaboration'
    name?: string // Repository name
    stars?: number // GitHub stars
    title?: string // Publication title
    venue?: string // Conference/journal venue
    year?: number | string // Publication year
    description?: string // Collaboration description
  }

  // Visualization related (added by frontend)
  id?: string // Node ID (generated by frontend)
  category?: number // Node category (for coloring)
  x?: number // Node position X (force-directed graph)
  y?: number // Node position Y (force-directed graph)
}

export interface AchievementNetwork {
  achievement_network: AchievementNode[]
}

// User data for achievement network generation
export interface UserData {
  name: string // Required: user's full name
  email?: string
  bio?: string
  location?: string
  education?: string
  [key: string]: any // Allow additional fields
}

// Social URLs for data aggregation
export interface SocialUrls {
  github?: string // GitHub profile URL
  linkedin?: string // LinkedIn profile URL
  scholar?: string // Google Scholar profile URL
  twitter?: string // Twitter/X profile URL
  website?: string // Personal website URL
  [key: string]: string | undefined // Allow additional platforms
}

// Achievement network generation request
export interface AchievementGenerationRequest {
  user_data: UserData
  social_urls?: SocialUrls
  mode?: 'sync' | 'async' // Execution mode (default: sync)
  weights?: Partial<WeightConfig> // Optional custom weights
}

// Network graph data for ECharts visualization
export interface NetworkGraphNode {
  id: string
  name: string
  value: number // Used for node size
  category?: number | string
  symbolSize?: number
}

export interface NetworkGraphEdge {
  source: string
  target: string
  value?: number // Used for edge width
}

export interface NetworkGraphCategory {
  name: string
}

export interface NetworkGraphData {
  nodes: NetworkGraphNode[]
  edges: NetworkGraphEdge[]
  categories?: NetworkGraphCategory[]
}
